version: '3'

services:
  proxy:
    image: traefik:2.0
    volumes:
      - ./:/var/www
      - /var/run/docker.sock:/var/run/docker.sock
      - ./.docker/config/traefik:/etc/traefik
    ports:
      - "80:80"
      - "443:443"

  app:
    image: rpopuc/php-fpm-nginx:7.4
    volumes:
      - ./:/var/www
    labels:
      - traefik.enable=true
      - traefik.http.routers.app_http.rule=Host(`${APP_DOMAIN}`)
      - traefik.http.routers.app.rule=Host(`${APP_DOMAIN}`)
      - traefik.http.routers.app_http.middlewares=secure@file
      - traefik.http.routers.app.tls=true

  postgres:
    image: postgres:13
    volumes:
      - ./.docker/data/postgres:/var/lib/postgresql/data
      - ./:/var/www
    environment:
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}

  newman:
    image: vdespa/newman
    volumes:
      - ./src-node:/etc/newman
    entrypoint: [""]
    command: >
      npm run server
    tty: true