version: '3'

services:
    #  newman run --env-var 'url=http://localhost:4010' http://app/api/v1/providers/cf2ecae6-a19f-484a-841d-bd44201b28e4/consumers/c9fbfa64-121a-40f7-af5e-f1f048195bc5.json
    proxy:
      image: traefik:2.0
      volumes:
        - ./:/var/www
        - /var/run/docker.sock:/var/run/docker.sock
        - ./.docker/config/traefik:/etc/traefik
      ports:
        - "80:80"
        - "443:443"
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.api_http.rule=Host(`proxy.local`)"
        - "traefik.http.routers.api_http.middlewares=secure@file"
        - "traefik.http.routers.api.rule=Host(`proxy.local`)"
        - "traefik.http.routers.api.service=api@internal"
        - "traefik.http.routers.api.tls=true"

    app:
      image: rpopuc/php-fpm-nginx:7.4
      volumes:
        - ./:/var/www
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.app_http.rule=Host(`register.local`)"
        - "traefik.http.routers.app_http.middlewares=secure@file"
        - "traefik.http.routers.app.rule=Host(`register.local`)"
        - "traefik.http.routers.app.tls=true"
      ports:
        - 8080:80

    postgres:
      image: postgres:13
      volumes:
        - ./.docker/data/postgres:/var/lib/postgresql/data
        - ./:/var/www
      environment:
        - POSTGRES_DB=app
        - POSTGRES_USER=app
        - POSTGRES_PASSWORD=app

    # redis:
    #   image: rpopuc/redis:4-alpine
    #   volumes:
    #     - ./.docker/data/redis:/data

    # worker:
    #   image: rpopuc/php-worker:7.3
    #   depends_on:
    #     - postgres
    #   volumes:
    #     - ./:/var/www
    #     - ~/.ssh:/home/laradock/.ssh

    newman:
      image: vdespa/newman
      volumes:
        - ./src-contracts:/contracts
        - ./src-node:/etc/newman
      entrypoint: [""]
      ports:
        - 3000:3000
      command: >
        npm run server
      tty: true